### ISSUE TITLE
Refactor lowering list of qubits (gate operands) in syntax_to_semantics.rs

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/openqasm3_parser#163]
Code like this:
https://github.com/Qiskit/openqasm3_parser/blob/dac0d7aaa54dc61f5d6909e98978ffbc0d02a84a/crates/oq3_semantics/src/syntax_to_semantics.rs#L393-L397

is repeated in several places. It should be factored into a function `from_qubit_list` or `ast_from_qubit_list`.

**Comment by abhamra** [comment]
I can work on this issue as well!

**Comment by atomgardner** [comment]
Dear @jlapeyre, could you please assign this issue to me so the UF robot can assign credit.
