### ISSUE TITLE
Implement function `from_designator` in syntax_to_semantics.rs

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/openqasm3_parser#170]
Analyzing designators :

* needs to be cleaner, with better error reporting
* is repeated and should be refactored.

This can be done by writing a function `fn from_designator`.

For example the similar small bits of code are repeated in many places:
https://github.com/Qiskit/openqasm3_parser/blob/22b55cc1582f1c98180099dca1f224d0fab11fd8/crates/oq3_semantics/src/syntax_to_semantics.rs#L286

https://github.com/Qiskit/openqasm3_parser/blob/22b55cc1582f1c98180099dca1f224d0fab11fd8/crates/oq3_semantics/src/syntax_to_semantics.rs#L409

https://github.com/Qiskit/openqasm3_parser/blob/22b55cc1582f1c98180099dca1f224d0fab11fd8/crates/oq3_semantics/src/syntax_to_semantics.rs#L949-L962

Furthermore, as we improve support for designators, for example including type checking, this refactoring will be even more important.

**Comment by abhamra** [comment]
To clarify, we want to reduce calls like `something.designator().and_then(|x| x.expr())` or `something.designator().unwrap().expr()` and instead be `something.from_designator()`, for consistency and to set-up a framework for improved error handling?

I'd love to be added to this issue; my plan was to create a simple function near the top of the file and leave it somewhat extensible with how it handles the unwrap() / and_then() call.

**Comment by abhamra** [comment]
This PR should satisfy the constraints of the issue; I think a separate issue could be created to bettter handle designator errors.
