### ISSUE TITLE
Revisit `allow(clippy::filter_map_identity)`

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/openqasm3_parser#19]
Revisit this

https://github.com/Qiskit/openqasm3_parser/blob/3f74976b5f35a2fafc0de3985e2697013e1a41c8/crates/source_file/src/source_file.rs#L200-L204

If this is really what we want, add a comment explaining why.

@jakelishman suggested this in response to the clippy complaint.
```rust
        .filter_map(|parse_item| match parse_item {
            synast::Stmt::Item(synast::Item::Include(include)) => {
                let file: synast::FilePath = include.file().unwrap();
                let file_path = file.to_string().unwrap();
                Some(parse_source_file(&PathBuf::from(file_path)))
            }
            _ => None,
        })
```

**Comment by jakelishman** [comment]
the point being just that `filter_map` is equivalent to `map` followed by `filter`.  At a minimum, the highlighted code block could replace the `filter_map` with a literal `filter` (which takes no mapping) and it'd do the same thing, but `filter_map` lets us combine the two into one immediately.

**Comment by jlapeyre** [comment]
To clarify what prompted me to add this
https://github.com/Qiskit/openqasm3_parser/blob/61bd9e4ac5996fdf036463c29a32d9cccb310f5e/crates/oq3_source_file/src/source_file.rs#L202,
removing that line makes clippy print
```rust
16 |         .filter_map(|x| x)
    |          ^^^^^^^^^^^^^^^^^ help: try: `flatten()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#filter_map_identity
    = note: `#[warn(clippy::filter_map_identity)]` on by default
```
