### ISSUE TITLE
Reduce prefix expression with unary minus wrapping literal, to literal with negative value

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/openqasm3_parser#195]
This has already been done for integer literals and float literals.
It remains to be done for timing literals. Because we have shoehorned imaginary literals into all code for handling timing literals (distinguishing finally when we build the ASG) the same reduction needs to be done for imaginary literals.

Following the pattern for integer and float literals will be quite boiler platey. But it is Rust after all.

For example, here is a part of the ASG structure for `-10.1 im;`:
```
expression: UnaryExpr(UnaryExpr { op: Minus, operand: TExpr { expression: Literal(ImaginaryFloat(FloatLiteral { value: "10.1" }))
```
For a plain-vanilla floating point literal `-10.1;` this is reduced to
```
expression: Literal(Float(FloatLiteral { value: "-10.1" }))
```

#### See also
* #92
* #94
* #190

**Comment by DotandLog** [comment]
Hello John,

I'd be happy to work on this issue.

Could you please provide more details about solving this problem so that I can easily understand where to start?

**Comment by atomgardner** [comment]
Dear @jlapeyre, could you please assign this issue to me so the UF robot can assign credit.
