### ISSUE TITLE
Parsing of assignment statements fails for `measure` instructions

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/openqasm3_parser#38]
At the moment, trying to use the OQ3 syntax for `measure` causes a panic during conversion to the semantic ASG.  It doesn't seem to matter whether the LHS is a simple identifier or an index expression.  For example, both of these examples panic:
```qasm
qubit q;
bit c;
c = measure q;
```
```qasm
qubit q;
bit[2] c;
c[0] = measure q;
```

The panics are both in this code block: https://github.com/Qiskit/openqasm3_parser/blob/8de396d98180e76c3acdc3d146acb8b2c5299b96/crates/oq3_semantics/src/syntax_to_semantics.rs#L570-L587.

The first panics on line 582, the second on line 575.

The panic message is (e.g.)
```python
import qiskit._qasm3
qiskit._qasm3.loads("bit c; qubit q; c = measure q;")
```
```
thread '<unnamed>' panicked at /Users/jake/.cargo/git/checkouts/openqasm3_parser-f3c8808ea3c5b583/8de396d/crates/oq3_semantics/src/syntax_to_semantics.rs:582:59:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[2], line 2
      1 import qiskit._qasm3
----> 2 qiskit._qasm3.loads("bit c; qubit q; c = measure q;")

PanicException: called `Option::unwrap()` on a `None` value
```

The backtrace is (unsurprisingly) totally unhelpful - the function call stack is _wildly_ inlined, and besides, all the interesting stuff is hidden in the parse structure.

**Comment by jakelishman** [comment]
Admittedly the Python-space "reproducer" is probably not very helpful, since `qiskit._qasm3` exists only on my laptop right now.

**Comment by blakejohnson** [comment]
FWIW, I see the same panic with a physical qubit identifier, i.e.:
```
OPENQASM 3.0;

bit[2] out;
out[0] = measure $0;
```

will panic when called via semdemo.
