### ISSUE TITLE
No-argument form of `barrier` unsupported in semantic analysis

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/openqasm3_parser#58]
A program such as
```qasm3
qubit[2] q;
barrier;
```
is [defined by the OQ3 spec to be equivalent to a barrier over all in-scope qubits](https://openqasm.com/language/delays.html#barrier-instruction).  At the moment it fails to convert in semantic analysis:
```text
thread '<unnamed>' panicked at /Users/jake/.cargo/git/checkouts/openqasm3_parser-f3c8808ea3c5b583/45556a9/crates/oq3_semantics/src/syntax_to_semantics.rs:491:18:
called `Option::unwrap()` on a `None` value
```

which is line 491 here: https://github.com/Qiskit/openqasm3_parser/blob/45556a9d2cfb0dd7a805006af3821e8454480a75/crates/oq3_semantics/src/syntax_to_semantics.rs#L488-L496

**Comment by jlapeyre** [comment]
I thought about this while implementing and forgot before I was finished. I could make
* qubit list an `Option`
* empty qubit list
* Separate node

`Option` sounds most rust-like. But based on experience, I think using an empty list is less cumbersome in the end.
