### ISSUE TITLE
Measure into an indexed identifier parses right-hand side incorrectly

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/openqasm3_parser#59]
Given the following OQ3:
```qasm3
qubit[2] q;
bit[2] c;
c[0] = measure q[0];
```
The resulting assignment-statement object for line 3 is:
```rust
Assignment {
    lvalue: IndexedIdentifier(IndexedIdentifier {
        identifier: Ok(SymbolId(1)),
        indexes: [ExpressionList(ExpressionList {
            expressions: [TExpr {
                expression: Literal(Int(IntLiteral { value: 0 })),
                ty: UInt(Some(128), True),
            }],
        })],
    }),
    rvalue: TExpr {
        expression: IndexedIdentifier(IndexedIdentifier {
            identifier: Ok(SymbolId(1)),
            indexes: [ExpressionList(ExpressionList {
                expressions: [TExpr {
                    expression: Literal(Int(IntLiteral { value: 0 })),
                    ty: UInt(Some(128), True),
                }],
            })],
        }),
        ty: ToDo,
    },
}
```

This misidentifies the RHS as only the indexed identifier, not the `MeasureExpression` that should contain the indexed identifier.

**Comment by jakelishman** [comment]
Flicking through the code now, I think I've got enough of a handle on the relevant internals to work this one through myself (which I wouldn't have if it required working closer to modifying the `ungram` or whatever).  I'll have a go and see.

**Comment by jlapeyre** [comment]
Ok. I'm back at a desk. I can look at this as well, if you don't get around to it.
I need to rewrite the notes on ungram et. al. so that it's more approachable.

**Comment by jlapeyre** [comment]
In case this might serve as a tutorial for someone else:
If I add `dbg!(assignment_stmt.expr().unwrap());` before this line
https://github.com/Qiskit/openqasm3_parser/blob/33a89a641837a82d219b791d499490fba202586d/crates/oq3_semantics/src/syntax_to_semantics.rs#L619

Then I see
```
[crates/oq3_semantics/src/syntax_to_semantics.rs:619] assignment_stmt.expr().unwrap() = IndexedIdentifier(
    IndexedIdentifier {
        syntax: INDEXED_IDENTIFIER@19..23
          IDENTIFIER@19..20
            IDENT@19..20 "c"
          INDEX_OPERATOR@20..23
            L_BRACK@20..21 "["
            EXPRESSION_LIST@21..22
              LITERAL@21..22
                INT_NUMBER@21..22 "0"
            R_BRACK@22..23 "]"
        ,
    },
)
```
Showing that this
https://github.com/Qiskit/openqasm3_parser/blob/33a89a641837a82d219b791d499490fba202586d/crates/oq3_syntax/src/ast/generated/nodes.rs#L258-L259

is picking out the wrong node.

**Comment by jakelishman** [comment]
My solution is entirely different to that and appears to work, but also, I think the ungram file is somehow out-of-date? There seems to be many places where it doesn't line up with the rest of the parsing.

**Comment by jakelishman** [comment]
Ah no never mind - my solution is part of it, but there's still some grammar/parser part that needs fixing as well.

**Comment by jlapeyre** [comment]
> There seems to be many places where it doesn't line up with the rest of the parsing.

That's correct it could use some cleaning up. The ungram file  is used to generate `nodes.rs` and `tokens.rs`, and nothing more. You can write similar code by hand in the `_ext.rs` files. The code that reads the ungram and generates `nodes.rs` is `./crates/oq3_syntax/src/tests/sourcegen_ast.rs`. The `_ext.rs` files exist in part for methods implemented for the structs that wrap `SyntaxNode` (in nodes.rs) . I've run across a couple of things that could be added to `sourcegen_ast.rs` to avoid writing some code by hand. But I never took the time to do it.

**Comment by jlapeyre** [comment]
Note that I treat `AssignmentStmt` apart from all the other binary operators. It might be easier or better to allow assignment to be caught by the binary operator code, and then pick it out later.

**Comment by jlapeyre** [comment]
I think fixing `Assignment` in the ungram file would be a good idea.

**Comment by jlapeyre** [comment]
I fixed this bug in https://github.com/Qiskit/openqasm3_parser/commit/d7fec5dd5fa798a1bd046372becad72164fb605e

I'll leave this open. If the other fix mentioned above is preferable, we can revert and apply it.

**Comment by jakelishman** [comment]
I think it's the right call to just stick with your fix.  I think longer term, we'll have to go for a tidy up in the CST, and I think there's a fair amount of stuff in both the lexer and the parser that's been carried over from the Rust language and isn't applicable to OQ3, but I was at risk at just falling down a complete rabbit hole trying to make changes in that vein for now.

**Comment by jlapeyre** [comment]
Over the weekend, I removed several leftovers from r-a. For example `NameRef`. And did some tidying up. But there is more that needs to be done.

**Comment by jakelishman** [comment]
My problems with the CST, lexer and parser are a bit deeper than just unneeded names - it's more about the structure of the language, how we go about tokenising it (we need a little bit of contextual tokenisation modes for proper OQ3 - the `OPENQASM` version string being the most obvious, but also the easiest to fix), and subsequently how we go about parsing the token stream.  There's decision structures in the parser that make sense for the target CST of Rust, but not of OQ3, which (I believe) is causing false parses at the moment, and the CST being a re-work of the Rust one has (imo) introduced a few points where the parser is harder to write cleanly than it could be.

But yeah, the point is that that doesn't _need_ doing now; as long as you're able to make bugfixes, it's not an immediate problem.
